make test.log.xml always conform to UTF-8
this is because the following test occasionally produces broken string
as __progname in the Jenkins environment on albireo
(I cannot reproduces the output by invoking the test manually, though):

blt/test.list: timer 5 pip_blt 8 24 ./pip_mutex 100 - process:preload

and Jenkins XML parsing fails as follows in that case:
Failed to read test report file /var/lib/jenkins/workspace/JOBNAME/src/test/test.log.xml
org.dom4j.DocumentException: Invalid byte 2 of 2-byte UTF-8 sequence.