do not use a new feature of C99, because gdb wants C90
gdb build fails with the following code:
pip_machdep.h:101:3: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
   int oldval = __sync_val_compare_and_swap( lock, 0, 1 );
   ^